theme: jekyll-theme-minimal
title: 'Genome-Wide Association Studies'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule
  - title: What is Bioinformatics/Genomics?
    url: https://raw.githubusercontent.com/ucdavis-bioinformatics-training/ucdavis-bioinformatics-training.presentations/master/genomics/Genomics_a_perspective_May_2020.pdf

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Zoom
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

  - heading: Prerequisites
  - title: Logging In
    url: intro/logging-in
  - title: CLI
    url: intro/command-line-intro
  - title: R
    url: intro/Intro2R
  - title: Cluster Computing
    url: intro/cluster

  - heading: Data Reduction
  - title: Project setup
    url: data_reduction/project-setup
  - title: Preprocessing raw data
    url: data_reduction/htstream
  - title: Alignment with BWA
    url: data_reduction/alignment
  - title: Variant calling using GATK
    url: data_reduction/variantcalling

  - heading: Data Analysis
  - title: Data Analysis
    url: data_analysis/GWAS

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Workshop Photos
    url: photos/photos
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-July-Genome-Wide-Association-Studies
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
